name: diffmat
channels:
    - defaults
    - pytorch
    - conda-forge
dependencies:
    - configargparse>=1.2.3
    - python=3.7
    - pytorch>=1.7.0
    - torchvision>=0.8.2
    - numpy>=1.18.5
    - matplotlib>=3.3.2
    - scipy>=1.4.1
    - ordered-set>=3.1.1
    - imageio>=2.5.0
    - gputil>=1.4.0
    - pip:
        - torchsummary>=1.5.1
